USE db_gamehub;

INSERT INTO Commentaire (contenu, date, id_utilisateur, id_jeu, note) VALUES
('Déçu par Uno, j''ai trouvé que le simplicité et son aspect familial était bâclé.','2023-12-06',1,1,1),
('Uno est intéressant grâce à son simplicité et son aspect familial, mais certains aspects mériteraient d''être améliorés.','2024-01-08',2,1,3),
('Une expérience mémorable avec Uno, entre simplicité et son aspect familial et ambiance conviviale.','2024-02-21',3,1,4),
('Uno allie simplicité et son aspect familial à une prise en main rapide, parfait pour tous les publics.','2023-06-13',4,1,4),
('Le concept de Uno et son simplicité et son aspect familial m''ont conquis, je le recommande vivement.','2023-05-10',5,1,5),
('Une expérience mémorable avec Monopoly, entre durée de partie intense et la stratégie d''achat et ambiance conviviale.','2023-08-30',6,2,5),
('J''aime bien Monopoly pour son durée de partie intense et la stratégie d''achat, cependant la rejouabilité est un peu limitée.','2023-10-05',7,2,3),
('Ce jeu brille par son durée de partie intense et la stratégie d''achat, Monopoly est désormais un de mes favoris.','2024-04-06',8,2,5),
('J''ai adoré Monopoly, surtout pour durée de partie intense et la stratégie d''achat, c''était un vrai plaisir à jouer.','2023-05-18',9,2,5),
('Pas fan de Monopoly, je trouve que la durée de partie intense et la stratégie d''achat n''est pas exploitées à son plein potentiel.','2023-10-18',10,2,1),
('Une expérience mémorable avec Skyjo, entre stratégie pour minimiser les points et ambiance conviviale.','2023-05-24',1,3,4),
('Le concept de Skyjo et son stratégie pour minimiser les points m''ont conquis, je le recommande vivement.','2023-09-19',2,3,4),
('Skyjo n''offre pas assez de challenge malgré son stratégie pour minimiser les points.','2023-11-01',3,3,2),
('J''ai adoré Skyjo, surtout pour stratégie pour minimiser les points, c''était un vrai plaisir à jouer.','2023-09-12',4,3,5),
('J''aime bien Skyjo pour son stratégie pour minimiser les points, cependant la rejouabilité est un peu limitée.','2023-05-29',5,3,3),
('Déçu par Cluedo, j''ai trouvé que l''ambiance suspense et les énigmes était bâclée.','2023-12-18',6,4,2),
('Cluedo est intéressant grâce à son ambiance suspense et les énigmes, mais certains aspects mériteraient d''être améliorés.','2023-06-25',7,4,3),
('Une expérience mémorable avec Cluedo, entre ambiance suspense et les énigmes et ambiance conviviale.','2023-11-14',8,4,4),
('Cluedo allie ambiance suspense et les énigmes à une prise en main rapide, parfait pour tous les publics.','2023-07-04',9,4,4),
('Le concept de Cluedo et son ambiance suspense et les énigmes m''ont conquis, je le recommande vivement.','2023-05-26',10,4,5),
('Une expérience mémorable avec Risk, entre montée d''adrénaline lors des conquêtes et ambiance conviviale.','2023-06-03',1,5,4),
('Le concept de Risk et sa montée d''adrénaline lors des conquêtes m''ont conquis, je le recommande vivement.','2023-08-15',2,5,5),
('Risk est intéressant grâce à sa montée d''adrénaline lors des conquêtes, mais certains aspects mériteraient d''être améliorés.','2023-10-10',3,5,3),
('J''ai adoré Risk, surtout pour montée d''adrénaline lors des conquêtes, c''était un vrai plaisir à jouer.','2023-08-28',4,5,5),
('Pas fan de Risk, je trouve que la montée d''adrénaline lors des conquêtes n''est pas exploitée à son plein potentiel.','2024-01-20',5,5,1),
('Une expérience mémorable avec Scrabble, entre défi linguistique et réflexion et ambiance conviviale.','2023-11-28',6,6,4),
('Le concept de Scrabble et son défi linguistique et réflexion m''ont conquis, je le recommande vivement.','2023-08-07',7,6,5),
('Scrabble est intéressant grâce à son défi linguistique et réflexion, mais certains aspects mériteraient d''être améliorés.','2023-09-22',8,6,3),
('J''ai adoré Scrabble, surtout pour défi linguistique et réflexion, c''était un vrai plaisir à jouer.','2023-05-14',9,6,5),
('Déçu par Scrabble, j''ai trouvé que le défi linguistique et réflexion était bâclé.','2024-02-17',10,6,2),
('Une expérience mémorable avec Dobble, entre vitesse et convivialité et ambiance conviviale.','2023-08-01',1,7,4),
('Le concept de Dobble et sa vitesse et convivialité m''ont conquis, je le recommande vivement.','2023-12-29',2,7,5),
('Dobble est intéressant grâce à sa vitesse et convivialité, mais certains aspects mériteraient d''être améliorés.','2023-10-13',3,7,3),
('J''ai adoré Dobble, surtout pour vitesse et convivialité, c''était un vrai plaisir à jouer.','2023-09-30',4,7,5),
('Déçu par Dobble, j''ai trouvé que la vitesse et convivialité était bâclée.','2023-11-08',5,7,2),
('Une expérience mémorable avec Jenga, entre suspense à chaque tour et ambiance conviviale.','2023-09-18',6,8,4),
('Le concept de Jenga et son suspense à chaque tour m''ont conquis, je le recommande vivement.','2024-04-03',7,8,5),
('Jenga est intéressant grâce à son suspense à chaque tour, mais certains aspects mériteraient d''être améliorés.','2023-11-24',8,8,3),
('J''ai adoré Jenga, surtout pour suspense à chaque tour, c''était un vrai plaisir à jouer.','2023-10-01',9,8,5),
('Pas fan de Jenga, je trouve que le suspense à chaque tour n''est pas exploité à son plein potentiel.','2023-05-20',10,8,1),
('Une expérience mémorable avec Twister, entre côté physique et les fous rires et ambiance conviviale.','2023-07-12',1,9,4),
('Le concept de Twister et son côté physique et les fous rires m''ont conquis, je le recommande vivement.','2023-09-16',2,9,5),
('Twister est intéressant grâce à son côté physique et les fous rires, mais certains aspects mériteraient d''être améliorés.','2023-05-17',3,9,3),
('J''ai adoré Twister, surtout pour côté physique et les fous rires, c''était un vrai plaisir à jouer.','2023-09-04',4,9,5),
('Déçu par Twister, j''ai trouvé que le côté physique et les fous rires était bâclé.','2024-02-27',5,9,2),
('Une expérience mémorable avec Puissance 4, entre réflexion tactique et ambiance conviviale.','2023-06-29',6,10,4),
('Le concept de Puissance 4 et sa réflexion tactique m''ont conquis, je le recommande vivement.','2024-04-05',7,10,5),
('Puissance 4 est intéressant grâce à sa réflexion tactique, mais certains aspects mériteraient d''être améliorés.','2023-12-09',8,10,3),
('J''ai adoré Puissance 4, surtout pour réflexion tactique, c''était un vrai plaisir à jouer.','2023-06-02',9,10,5),
('Pas fan de Puissance 4, je trouve que la réflexion tactique n''est pas exploitée à son plein potentiel.','2023-10-11',10,10,1),
('Une expérience mémorable avec Trivial Pursuit, entre diversité des questions culturelles et ambiance conviviale.','2023-06-27',1,11,4),
('Le concept de Trivial Pursuit et sa diversité des questions culturelles m''ont conquis, je le recommande vivement.','2023-08-26',2,11,5),
('Trivial Pursuit est intéressant grâce à sa diversité des questions culturelles, mais certains aspects mériteraient d''être améliorés.','2024-01-15',3,11,3),
('J''ai adoré Trivial Pursuit, surtout pour diversité des questions culturelles, c''était un vrai plaisir à jouer.','2023-12-22',4,11,5),
('Déçu par Trivial Pursuit, j''ai trouvé que la diversité des questions culturelles était bâclée.','2023-05-29',5,11,2),
('Une expérience mémorable avec Pictionary, entre expression artistique rapide et ambiance conviviale.','2023-11-19',6,12,4),
('Le concept de Pictionary et son expression artistique rapide m''ont conquis, je le recommande vivement.','2023-10-23',7,12,5),
('Pictionary est intéressant grâce à son expression artistique rapide, mais certains aspects mériteraient d''être améliorés.','2023-05-14',8,12,3),
('J''ai adoré Pictionary, surtout pour expression artistique rapide, c''était un vrai plaisir à jouer.','2024-01-09',9,12,5),
('Pas fan de Pictionary, je trouve que l''expression artistique rapide n''est pas exploitée à son plein potentiel.','2023-10-04',10,12,1),
('Une expérience mémorable avec Mille Bornes, entre esprit de compétition familiale et ambiance conviviale.','2023-05-18',1,13,4),
('Le concept de Mille Bornes et son esprit de compétition familiale m''ont conquis, je le recommande vivement.','2023-09-07',2,13,5),
('Mille Bornes est intéressant grâce à son esprit de compétition familiale, mais certains aspects mériteraient d''être améliorés.','2023-08-19',3,13,3),
('J''ai adoré Mille Bornes, surtout pour esprit de compétition familiale, c''était un vrai plaisir à jouer.','2023-07-09',4,13,5),
('Déçu par Mille Bornes, j''ai trouvé que l''esprit de compétition familiale était bâclé.','2023-06-15',5,13,2),
('Une expérience mémorable avec Time''s Up!, entre effervescence et rapidité et ambiance conviviale.','2023-08-12',6,14,4),
('Le concept de Time''s Up! et son effervescence et rapidité m''ont conquis, je le recommande vivement.','2024-02-04',7,14,5),
('Time''s Up! est intéressant grâce à son effervescence et rapidité, mais certains aspects mériteraient d''être améliorés.','2023-07-11',8,14,3),
('J''ai adoré Time''s Up!, surtout pour effervescence et rapidité, c''était un vrai plaisir à jouer.','2023-06-11',9,14,5),
('Pas fan de Time''s Up!, je trouve que l''effervescence et rapidité n''est pas exploitée à son plein potentiel.','2023-10-29',10,14,1),
('Une expérience mémorable avec Les Loups-Garous de Thiercelieux, entre psychologie et débats et ambiance conviviale.','2023-07-21',1,15,4),
('Le concept de Les Loups-Garous de Thiercelieux et sa psychologie et débats m''ont conquis, je le recommande vivement.','2023-08-05',2,15,5),
('Les Loups-Garous de Thiercelieux est intéressant grâce à sa psychologie et débats, mais certains aspects mériteraient d''être améliorés.','2023-05-27',3,15,3),
('J''ai adoré Les Loups-Garous de Thiercelieux, surtout pour psychologie et débats, c''était un vrai plaisir à jouer.','2023-12-17',4,15,5),
('Déçu par Les Loups-Garous de Thiercelieux, j''ai trouvé que la psychologie et débats était bâclée.','2024-03-03',5,15,2),
('Une expérience mémorable avec Labyrinthe, entre logique et plateau changeant et ambiance conviviale.','2023-10-21',6,16,4),
('Le concept de Labyrinthe et sa logique et plateau changeant m''ont conquis, je le recommande vivement.','2023-06-06',7,16,5),
('Labyrinthe est intéressant grâce à sa logique et plateau changeant, mais certains aspects mériteraient d''être améliorés.','2023-10-16',8,16,3),
('J''ai adoré Labyrinthe, surtout pour logique et plateau changeant, c''était un vrai plaisir à jouer.','2024-02-09',9,16,5),
('Pas fan de Labyrinthe, je trouve que la logique et plateau changeant n''est pas exploitée à son plein potentiel.','2023-09-02',10,16,1),
('Une expérience mémorable avec La Bonne Paye, entre gestion financière ludique et ambiance conviviale.','2023-09-27',1,17,4),
('Le concept de La Bonne Paye et sa gestion financière ludique m''ont conquis, je le recommande vivement.','2023-05-08',2,17,5),
('La Bonne Paye est intéressant grâce à sa gestion financière ludique, mais certains aspects mériteraient d''être améliorés.','2023-12-08',3,17,3),
('J''ai adoré La Bonne Paye, surtout pour gestion financière ludique, c''était un vrai plaisir à jouer.','2024-03-13',4,17,5),
('Déçu par La Bonne Paye, j''ai trouvé que la gestion financière ludique était bâclée.','2023-11-21',5,17,2),
('Une expérience mémorable avec 7 Familles, entre nostalgie et simplicité et ambiance conviviale.','2023-08-22',6,18,4),
('Une expérience mémorable avec 7 Familles, entre nostalgie et simplicité et ambiance conviviale.','2023-07-28',7,18,5),
('Déçu par 7 Familles, j''ai trouvé que la nostalgie et simplicité était bâclée.','2023-11-13',8,18,2),
('Le concept de 7 Familles et son nostalgie et simplicité m''ont conquis, je le recommande vivement.','2023-09-28',9,18,5),
('7 Familles est intéressant grâce à son nostalgie et simplicité, mais certains aspects mériteraient d''être améliorés.','2024-04-24',10,18,3),
('Qui Est-ce? allie anticipation et bluff à une prise en main rapide, parfait pour tous les publics.','2024-05-03',1,19,4),
('Le concept de Qui Est-ce? et son anticipation et bluff m''ont conquis, je le recommande vivement.','2023-11-05',2,19,5),
('Qui Est-ce? est intéressant grâce à son anticipation et bluff, mais certains aspects mériteraient d''être améliorés.','2024-01-06',3,19,3),
('Ce jeu brille par son anticipation et bluff, Qui Est-ce? est désormais un de mes favoris.','2023-11-03',4,19,5),
('Déçu par Qui Est-ce?, j''ai trouvé que l''anticipation et bluff était bâclée.','2023-11-04',5,19,2),
('Une expérience mémorable avec Burger Quiz, entre humour et ambiance décalée et ambiance conviviale.','2023-11-29',6,20,5),
('Assez bon Burger Quiz pour son humour et ambiance décalée, mais je ne suis pas certain d''y rejouer souvent.','2024-04-04',7,20,3),
('J''ai adoré Burger Quiz, surtout pour humour et ambiance décalée, c''était un vrai plaisir à jouer.','2023-05-20',8,20,4),
('Burger Quiz allie humour et ambiance décalée à une prise en main rapide, parfait pour tous les publics.','2023-10-24',9,20,4),
('Déçu par Burger Quiz, j''ai trouvé que l''humour et ambiance décalée était bâclée.','2023-11-13',10,20,2),
('Une expérience mémorable avec Jenga, entre la durée de partie et l''interaction entre joueurs.', '2023-07-13', 3, 8, 4),
('Déçu par Burger Quiz, je trouve que l''originalité n''est pas exploité à son plein potentiel.', '2023-08-29', 8, 20, 2),
('J''ai adoré Cluedo, surtout pour le suspense, c''était un vrai plaisir à jouer.', '2023-10-05', 1, 4, 5),
('Une expérience mémorable avec 7 Familles, entre l''originalité et la durée de partie.', '2024-04-15', 10, 18, 1),
('Déçu par La Bonne Paye, je trouve que la convivialité n''est pas exploité à son plein potentiel.', '2023-08-08', 10, 17, 2),
('Pictionary est intéressant grâce à son la convivialité, mais certains aspects mériteraient d''être améliorés.', '2024-02-26', 9, 12, 1),
('J''ai adoré Dobble, surtout pour la durée de partie, c''était un vrai plaisir à jouer.', '2023-06-12', 2, 7, 1),
('Une expérience mémorable avec 7 Familles, entre le rythme et les règles simples.', '2023-06-07', 3, 18, 1),
('Une expérience mémorable avec La Bonne Paye, entre la stratégie et la rejouabilité.', '2023-06-01', 6, 17, 4),
('Uno est intéressant grâce à son la convivialité, mais certains aspects mériteraient d''être améliorés.', '2023-08-07', 1, 1, 4),
('J''aime bien Puissance 4 pour son la durée de partie et la convivialité, cependant la rejouabilité est un peu limitée.', '2023-10-06', 6, 10, 1),
('Pas fan de Time''s Up!, je trouve que l''ambiance et la stratégie était bâclée.', '2024-03-24', 5, 14, 5),
('Une expérience mémorable avec Uno, entre l''originalité et la rejouabilité.', '2024-04-01', 7, 1, 5),
('J''aime bien Scrabble pour son la rejouabilité et la difficulté, cependant la rejouabilité est un peu limitée.', '2024-01-21', 2, 6, 5),
('Une expérience mémorable avec Uno, entre la stratégie et l''ambiance.', '2023-06-12', 5, 1, 3),
('Une expérience mémorable avec Labyrinthe, entre l''ambiance et les règles simples.', '2023-07-15', 7, 16, 4),
('J''ai adoré Cluedo, surtout pour l''interaction entre joueurs, c''était un vrai plaisir à jouer.', '2023-09-22', 3, 4, 5),
('Le concept de Risk et son la rejouabilité m''ont conquis, je le recommande vivement.', '2023-12-05', 5, 5, 4),
('Déçu par Uno, je trouve que la durée de partie n''est pas exploité à son plein potentiel.', '2023-11-30', 9, 1, 2),
('Skyjo allie la stratégie et le rythme à une prise en main rapide, parfait pour tous les publics.', '2024-01-10', 2, 3, 5),
('Monopoly est intéressant grâce à son l''originalité, mais certains aspects mériteraient d''être améliorés.', '2023-08-18', 6, 2, 3),
('J''aime bien Scrabble pour son le suspense et la difficulté, cependant la rejouabilité est un peu limitée.', '2023-11-07', 8, 6, 2),
('Pas fan de Dobble, je trouve que le les graphismes et la convivialité était bâclé.', '2023-10-03', 1, 7, 1),
('Une expérience mémorable avec Pictionary, entre les graphismes et la durée de partie.', '2023-12-28', 4, 12, 4),
('J''ai adoré Jenga, surtout pour le suspense, c''était un vrai plaisir à jouer.', '2024-02-14', 10, 8, 5),
('Le concept de Puissance 4 et son l''interaction entre joueurs m''ont conquis, je le recommande vivement.', '2023-05-25', 7, 10, 4),
('Déçu par Trivial Pursuit, je trouve que la difficulté n''est pas exploité à son plein potentiel.', '2023-06-19', 2, 11, 2),
('Les Loups-Garous de Thiercelieux est intéressant grâce à sa psychologie et débats, mais certains aspects mériteraient d''être améliorés.', '2023-10-09', 5, 15, 3),
('Une expérience mémorable avec Burger Quiz, entre l''originalité et l''humour.', '2023-07-30', 3, 20, 4),
('Time''s Up! allie l''effervescence et rapidité à une prise en main rapide, parfait pour tous les publics.', '2024-03-02', 1, 14, 5),
('J''aime bien Mille Bornes pour son la convivialité et la stratégie, cependant la rejouabilité est un peu limitée.', '2023-05-18', 6, 13, 3),
('Pas fan de Qui Est-ce?, je trouve que le suspense et bluff était bâclé.', '2023-09-05', 9, 19, 1),
('Une expérience mémorable avec 7 Familles, entre l''originalité et la simplicité.', '2023-11-16', 4, 18, 5),
('Le concept de La Bonne Paye et son la gestion financière ludique m''ont conquis, je le recommande vivement.', '2023-08-24', 10, 17, 5),
('J''ai adoré Risk, surtout pour la difficulté, c''était un vrai plaisir à jouer.', '2023-10-12', 2, 5, 5),
('Déçu par Uno, je trouve que l''originalité n''est pas exploité à son plein potentiel.', '2023-06-22', 8, 1, 2),
('Skyjo est intéressant grâce à son la coopération entre joueurs, mais certains aspects mériteraient d''être améliorés.', '2023-07-29', 3, 3, 3),
('J''ai adoré Pictionary, surtout pour la créativité, c''était un vrai plaisir à jouer.', '2023-12-02', 7, 12, 5),
('Pas fan de Jenga, je trouve que le suspense et la difficulté était bâclé.', '2023-11-19', 5, 16, 1),
('Le concept de Monopoly et son le rythme m''ont conquis, je le recommande vivement.', '2023-07-08', 1, 2, 4),
('Trivial Pursuit allie la diversité des questions culturelles et la réflexion à une prise en main rapide, parfait pour tous les publics.', '2023-05-30', 4, 11, 4),
('Une expérience mémorable avec La Bonne Paye, entre la stratégie et la gestion financière ludique.', '2023-09-17', 6, 17, 5),
('Déçu par Scrabble, je trouve que la rejouabilité n''est pas exploité à son plein potentiel.', '2023-08-11', 9, 6, 2),
('J''aime bien Les Loups-Garous de Thiercelieux pour son la psychologie et les débats, cependant la rejouabilité est un peu limitée.', '2023-10-27', 10, 15, 3),
('Pas fan de Twister, je trouve que le rythme et les fous rires était bâclé.', '2024-03-05', 2, 9, 1),
('Le concept de Dobble et son la vitesse m''ont conquis, je le recommande vivement.', '2023-06-14', 7, 7, 4),
('Une expérience mémorable avec Puissance 4, entre la réflexion tactique et la stratégie.', '2023-11-23', 3, 10, 5),
('Burger Quiz est intéressant grâce à son l''humour, mais certains aspects mériteraient d''être améliorés.', '2023-07-12', 8, 20, 3),
('J''ai adoré Skyjo, surtout pour la stratégie, c''était un vrai plaisir à jouer.', '2024-01-29', 4, 3, 5),
('Déçu par Labyrinthe, je trouve que la logique et le plateau changeant n''est pas exploité à son plein potentiel.', '2023-06-07', 6, 16, 2),
('Le concept de Time''s Up! et son l''effervescence m''ont conquis, je le recommande vivement.', '2023-12-19', 1, 14, 5),
('Pas fan de Pictionary, je trouve que la créativité et la rapidité était bâclé.', '2023-09-03', 5, 12, 1),
('Une expérience mémorable avec Cluedo, entre l''ambiance et les énigmes.', '2023-07-25', 9, 4, 4),
('J''aime bien 7 Familles pour son la nostalgie et la simplicité, cependant la rejouabilité est un peu limitée.', '2023-05-28', 2, 18, 3),
('Risk allie la stratégie et la conquête à une prise en main rapide, parfait pour tous les publics.', '2023-08-31', 10, 5, 4),
('Déçu par Trivial Pursuit, je trouve que la diversité des questions culturelles n''est pas exploité à son plein potentiel.', '2023-06-18', 7, 11, 2),
('J''aime bien Uno pour son la convivialité et l''interaction entre joueurs, cependant la rejouabilité est un peu limitée.', '2023-10-15', 6, 1, 3),
('Une expérience mémorable avec La Bonne Paye, entre la gestion financière ludique et la convivialité.', '2024-02-27', 3, 17, 5),
('J''ai adoré 7 Familles, surtout pour la difficulté, c''était un vrai plaisir à jouer.', '2024-12-15', 9, 18, 5),
('Une expérience mémorable avec Risk, entre l''originalité et la rejouabilité.', '2025-03-01', 5, 5, 1),
('Le concept de Time et son la durée de partie m''ont conquis, je le recommande vivement.', '2024-09-01', 1, 14, 3),
('Déçu par Time, je trouve que la convivialité n''est pas exploité à son plein potentiel.', '2025-03-22', 10, 14, 3),
('J''ai adoré Twister, surtout pour la rejouabilité, c''était un vrai plaisir à jouer.', '2024-11-02', 4, 9, 1),
('J''ai adoré Twister, surtout pour la convivialité, c''était un vrai plaisir à jouer.', '2024-07-26', 4, 9, 5),
('Déçu par Puissance 4, je trouve que l''interaction entre joueurs n''est pas exploité à son plein potentiel.', '2024-06-29', 9, 10, 5),
('Déçu par Labyrinthe, je trouve que l''ambiance n''est pas exploité à son plein potentiel.', '2024-10-10', 4, 16, 4),
('Le concept de Dobble et son la rejouabilité m''ont conquis, je le recommande vivement.', '2024-08-06', 3, 7, 1),
('Pas fan de 7 Familles, je trouve que le les règles simples et la rejouabilité était bâclé.', '2025-01-13', 4, 18, 3),
('J''aime bien Cluedo pour son le suspense et l''interaction entre joueurs, cependant la rejouabilité est un peu limitée.', '2024-07-07', 3, 4, 2),
('J''ai adoré Scrabble, surtout pour les graphismes, c''était un vrai plaisir à jouer.', '2024-05-11', 6, 6, 2),
('Le concept de Cluedo et son la stratégie m''ont conquis, je le recommande vivement.', '2025-03-07', 1, 4, 2),
('J''aime bien Jenga pour son le suspense et la convivialité, cependant la rejouabilité est un peu limitée.', '2024-06-26', 8, 8, 2),
('Labyrinthe est intéressant grâce à son le suspense, mais certains aspects mériteraient d''être améliorés.', '2025-04-07', 5, 16, 2),
('Le concept de Time et son les graphismes m''ont conquis, je le recommande vivement.', '2025-02-09', 3, 14, 3),
('J''ai adoré Cluedo, surtout pour la durée de partie, c''était un vrai plaisir à jouer.', '2024-12-09', 3, 4, 1),
('J''ai adoré Les Loups-Garous de Thiercelieux, surtout pour l''originalité, c''était un vrai plaisir à jouer.', '2024-11-03', 10, 15, 1),
('Pas fan de Pictionary, je trouve que le le suspense et l''originalité était bâclé.', '2025-03-20', 8, 12, 1),
('Le concept de Skyjo et son l''originalité m''ont conquis, je le recommande vivement.', '2024-10-21', 9, 3, 5),
('Le concept de Monopoly et son la rejouabilité m''ont conquis, je le recommande vivement.', '2025-04-28', 2, 2, 5),
('Le concept de Jenga et son le rythme m''ont conquis, je le recommande vivement.', '2024-11-08', 10, 8, 2),
('Le concept de Dobble et son l''ambiance m''ont conquis, je le recommande vivement.', '2025-04-27', 5, 7, 1),
('J''ai adoré Risk, surtout pour la durée de partie, c''était un vrai plaisir à jouer.', '2024-11-20', 3, 5, 2),
('J''ai adoré Burger Quiz, surtout pour l''ambiance, c''était un vrai plaisir à jouer.', '2024-11-28', 7, 20, 3),
('Une expérience mémorable avec Risk, entre l''originalité et le suspense.', '2024-06-03', 4, 5, 1),
('Puissance 4 allie la difficulté et le rythme à une prise en main rapide, parfait pour tous les publics.', '2025-01-21', 10, 10, 1),
('Déçu par Twister, je trouve que l''ambiance n''est pas exploité à son plein potentiel.', '2025-02-20', 9, 9, 4),
('J''aime bien Monopoly pour son la rejouabilité et l''ambiance, cependant la rejouabilité est un peu limitée.', '2024-09-23', 3, 2, 3),
('J''ai adoré Cluedo, surtout pour le suspense, c''était un vrai plaisir à jouer.', '2024-08-08', 4, 4, 2),
('Le concept de Cluedo et son la stratégie m''ont conquis, je le recommande vivement.', '2024-10-08', 5, 4, 3),
('Une expérience mémorable avec Jenga, entre l''interaction entre joueurs et le rythme.', '2025-01-10', 6, 8, 4),
('J''aime bien Scrabble pour son la rejouabilité et le rythme, cependant la rejouabilité est un peu limitée.', '2025-01-18', 4, 6, 2),
('Mille Bornes allie le rythme et la rejouabilité à une prise en main rapide, parfait pour tous les publics.', '2025-01-11', 6, 13, 4),
('J''ai adoré Les Loups-Garous de Thiercelieux, surtout pour le rythme, c''était un vrai plaisir à jouer.', '2024-12-27', 5, 15, 2),
('Pas fan de Skyjo, je trouve que le les graphismes et l''ambiance était bâclé.', '2024-10-01', 5, 3, 4),
('Qui Est-ce? allie la stratégie et la durée de partie à une prise en main rapide, parfait pour tous les publics.', '2025-03-20', 10, 19, 5),
('Skyjo allie l''ambiance et l''originalité à une prise en main rapide, parfait pour tous les publics.', '2024-07-12', 1, 3, 1),
('Pas fan de Puissance 4, je trouve que le la stratégie et le suspense était bâclé.', '2024-05-20', 7, 10, 2),
('Le concept de 7 Familles et son l''ambiance m''ont conquis, je le recommande vivement.', '2024-08-13', 4, 18, 2),
('Une expérience mémorable avec Scrabble, entre la difficulté et l''interaction entre joueurs.', '2025-04-10', 4, 6, 2),
('J''ai adoré Skyjo, surtout pour la convivialité, c''était un vrai plaisir à jouer.', '2024-11-26', 5, 3, 4),
('Pas fan de Mille Bornes, je trouve que le la durée de partie et l''ambiance était bâclé.', '2024-10-25', 3, 13, 2),
('Scrabble allie les graphismes et la stratégie à une prise en main rapide, parfait pour tous les publics.', '2025-04-17', 4, 6, 2),
('Une expérience mémorable avec Qui Est-ce?, entre l''ambiance et les graphismes.', '2024-06-26', 3, 19, 2),
('J''ai adoré Jenga, surtout pour l''originalité, c''était un vrai plaisir à jouer.', '2024-09-23', 4, 8, 2),
('Twister est intéressant grâce à son la durée de partie, mais certains aspects mériteraient d''être améliorés.', '2024-05-12', 1, 9, 1),
('Déçu par Puissance 4, je trouve que la durée de partie n''est pas exploité à son plein potentiel.', '2024-07-03', 7, 10, 4),
('7 Familles allie les règles simples et le rythme à une prise en main rapide, parfait pour tous les publics.', '2024-08-23', 7, 18, 5),
('Une expérience mémorable avec Risk, entre l''ambiance et le suspense.', '2024-09-17', 10, 5, 2),
('Skyjo est intéressant grâce à son la difficulté, mais certains aspects mériteraient d''être améliorés.', '2024-11-16', 9, 3, 2),
('J''aime bien Dobble pour son le suspense et la rejouabilité, cependant la rejouabilité est un peu limitée.', '2024-10-07', 5, 7, 4),
('Une expérience mémorable avec Time, entre le rythme et l''interaction entre joueurs.', '2024-08-26', 7, 14, 2),
('Pas fan de Skyjo, je trouve que le la convivialité et la durée de partie était bâclé.', '2025-04-27', 9, 3, 3),
('Pas fan de Cluedo, je trouve que le l''originalité et la rejouabilité était bâclé.', '2024-05-12', 3, 4, 2),
('Trivial Pursuit allie le suspense et l''originalité à une prise en main rapide, parfait pour tous les publics.', '2024-11-20', 1, 11, 5),
('Le concept de Skyjo et son la stratégie m''ont conquis, je le recommande vivement.', '2024-09-01', 10, 3, 2),
('Une expérience mémorable avec Jenga, entre les règles simples et l''originalité.', '2025-04-27', 3, 8, 1),
('Pas fan de Burger Quiz, je trouve que le la convivialité et les règles simples était bâclé.', '2024-07-29', 1, 20, 4),
('Le concept de Les Loups-Garous de Thiercelieux et son la difficulté m''ont conquis, je le recommande vivement.', '2025-05-04', 7, 15, 4),
('Pas fan de Dobble, je trouve que le l''ambiance et la stratégie était bâclé.', '2024-09-25', 8, 7, 1),
('Pas fan de Jenga, je trouve que le les graphismes et le rythme était bâclé.', '2024-09-30', 9, 8, 4),
('J''ai adoré Monopoly, surtout pour le rythme, c''était un vrai plaisir à jouer.', '2025-01-17', 5, 2, 5),
('Déçu par Uno, je trouve que la difficulté n''est pas exploité à son plein potentiel.', '2024-05-21', 7, 1, 1),
('J''ai adoré Scrabble, surtout pour l''interaction entre joueurs, c''était un vrai plaisir à jouer.', '2024-07-15', 8, 6, 2),
('Le concept de Les Loups-Garous de Thiercelieux et son l''ambiance m''ont conquis, je le recommande vivement.', '2024-09-04', 2, 15, 1),
('Une expérience mémorable avec Scrabble, entre la convivialité et le rythme.', '2025-02-17', 7, 6, 1),
('Le concept de Trivial Pursuit et son la rejouabilité m''ont conquis, je le recommande vivement.', '2025-01-13', 4, 11, 4),
('Déçu par La Bonne Paye, je trouve que l''interaction entre joueurs n''est pas exploité à son plein potentiel.', '2024-12-14', 1, 17, 4),
('Déçu par Mille Bornes, je trouve que l''ambiance n''est pas exploité à son plein potentiel.', '2024-05-18', 8, 13, 3),
('Le concept de Uno et son les règles simples m''ont conquis, je le recommande vivement.', '2024-05-10', 8, 1, 2),
('Labyrinthe allie la difficulté et l''ambiance à une prise en main rapide, parfait pour tous les publics.', '2024-12-24', 10, 16, 1),
('Scrabble allie la stratégie et les graphismes à une prise en main rapide, parfait pour tous les publics.', '2025-01-02', 5, 6, 1),
('J''ai adoré Trivial Pursuit, surtout pour l''interaction entre joueurs, c''était un vrai plaisir à jouer.', '2025-02-04', 1, 11, 1),
('Dobble allie la rejouabilité et les règles simples à une prise en main rapide, parfait pour tous les publics.', '2024-09-16', 2, 7, 5),
('7 Familles allie le rythme et la difficulté à une prise en main rapide, parfait pour tous les publics.', '2024-07-30', 3, 18, 1),
('Pas fan de Risk, je trouve que le l''originalité et le suspense était bâclé.', '2024-07-08', 6, 5, 2),
('Pas fan de Uno, je trouve que le le rythme et la durée de partie était bâclé.', '2024-08-26', 4, 1, 2),
('Pas fan de Time, je trouve que le l''interaction entre joueurs et le suspense était bâclé.', '2024-11-27', 2, 14, 5),
('Pas fan de Scrabble, je trouve que le la stratégie et la convivialité était bâclé.', '2025-03-14', 8, 6, 2),
('Le concept de Trivial Pursuit et son les graphismes m''ont conquis, je le recommande vivement.', '2025-01-03', 8, 11, 1),
('Pas fan de Monopoly, je trouve que le la stratégie et la durée de partie était bâclé.', '2025-02-14', 9, 2, 3),
('Le concept de Pictionary et son la durée de partie m''ont conquis, je le recommande vivement.', '2024-08-23', 1, 12, 2),
('J''aime bien Cluedo pour son la difficulté et les règles simples, cependant la rejouabilité est un peu limitée.', '2024-05-29', 1, 4, 2),
('Pas fan de Les Loups-Garous de Thiercelieux, je trouve que le l''originalité et la difficulté était bâclé.', '2025-04-29', 2, 15, 4),
('Une expérience mémorable avec Risk, entre la difficulté et l''originalité.', '2024-07-29', 8, 5, 2),
('J''aime bien Pictionary pour son l''interaction entre joueurs et la difficulté, cependant la rejouabilité est un peu limitée.', '2024-08-10', 10, 12, 2),
('Skyjo allie la durée de partie et les graphismes à une prise en main rapide, parfait pour tous les publics.', '2025-04-04', 3, 3, 4),
('Qui Est-ce? allie la convivialité et l''interaction entre joueurs à une prise en main rapide, parfait pour tous les publics.', '2025-01-07', 1, 19, 4),
('J''ai adoré 7 Familles, surtout pour l''ambiance, c''était un vrai plaisir à jouer.', '2025-01-12', 1, 18, 5),
('Le concept de Time et son l''ambiance m''ont conquis, je le recommande vivement.', '2025-04-04', 4, 14, 3),
('J''aime bien Time pour son le suspense et les graphismes, cependant la rejouabilité est un peu limitée.', '2025-02-11', 10, 14, 1),
('J''ai adoré La Bonne Paye, surtout pour la convivialité, c''était un vrai plaisir à jouer.', '2024-11-03', 9, 17, 1),
('Jenga est intéressant grâce à son le suspense, mais certains aspects mériteraient d''être améliorés.', '2024-06-05', 4, 8, 5),
('Pas fan de Scrabble, je trouve que le la stratégie et la rejouabilité était bâclé.', '2024-10-14', 7, 6, 1),
('J''ai adoré Pictionary, surtout pour le rythme, c''était un vrai plaisir à jouer.', '2024-07-18', 8, 12, 1),
('J''ai adoré Scrabble, surtout pour les règles simples, c''était un vrai plaisir à jouer.', '2024-10-07', 5, 6, 3),
('Pas fan de Dobble, je trouve que le la durée de partie et le suspense était bâclé.', '2024-09-30', 8, 7, 4),
('Pas fan de La Bonne Paye, je trouve que le le rythme et la rejouabilité était bâclé.', '2024-06-27', 6, 17, 1),
('Déçu par La Bonne Paye, je trouve que le rythme n''est pas exploité à son plein potentiel.', '2025-01-28', 2, 17, 5),
('Déçu par Dobble, je trouve que les règles simples n''est pas exploité à son plein potentiel.', '2024-09-03', 6, 7, 2),
('Pas fan de Dobble, je trouve que le l''interaction entre joueurs et la stratégie était bâclé.', '2024-10-25', 7, 7, 5),
('Scrabble est intéressant grâce à son le rythme, mais certains aspects mériteraient d''être améliorés.', '2024-05-31', 6, 6, 5),
('J''ai adoré Trivial Pursuit, surtout pour l''ambiance, c''était un vrai plaisir à jouer.', '2024-08-24', 2, 11, 4),
('Pas fan de Skyjo, je trouve que le la difficulté et le suspense était bâclé.', '2024-07-04', 7, 3, 4),
('Le concept de Twister et son la rejouabilité m''ont conquis, je le recommande vivement.', '2024-12-27', 2, 9, 3),
('J''aime bien Jenga pour son la rejouabilité et la convivialité, cependant la rejouabilité est un peu limitée.', '2024-08-23', 6, 8, 5),
('Une expérience mémorable avec Burger Quiz, entre le rythme et les graphismes.', '2024-08-07', 1, 20, 3),
('J''aime bien Burger Quiz pour son l''ambiance et la rejouabilité, cependant la rejouabilité est un peu limitée.', '2025-04-27', 3, 20, 2),
('Time allie les règles simples et le rythme à une prise en main rapide, parfait pour tous les publics.', '2024-07-06', 2, 14, 3),
('J''aime bien Les Loups-Garous de Thiercelieux pour son la difficulté et le rythme, cependant la rejouabilité est un peu limitée.', '2024-12-11', 2, 15, 4),
('Pas fan de Dobble, je trouve que le la durée de partie et les graphismes était bâclé.', '2024-07-08', 2, 7, 2),
('Pictionary allie la difficulté et l''interaction entre joueurs à une prise en main rapide, parfait pour tous les publics.', '2024-07-31', 6, 12, 1),
('Pas fan de Jenga, je trouve que le le suspense et la durée de partie était bâclé.', '2024-07-03', 7, 8, 3),
('Une expérience mémorable avec Puissance 4, entre l''ambiance et les règles simples.', '2024-05-23', 6, 10, 2),
('J''ai adoré Dobble, surtout pour l''ambiance, c''était un vrai plaisir à jouer.', '2024-07-21', 7, 7, 4),
('Déçu par Twister, je trouve que les règles simples n''est pas exploité à son plein potentiel.', '2024-08-28', 5, 9, 1),
('Le concept de Skyjo et son la stratégie m''ont conquis, je le recommande vivement.', '2024-06-08', 6, 3, 1),
('J''aime bien Labyrinthe pour son le suspense et la rejouabilité, cependant la rejouabilité est un peu limitée.', '2024-09-18', 7, 16, 2),
('Risk allie l''interaction entre joueurs et le suspense à une prise en main rapide, parfait pour tous les publics.', '2025-02-01', 6, 5, 1),
('J''ai adoré Les Loups-Garous de Thiercelieux, surtout pour la convivialité, c''était un vrai plaisir à jouer.', '2024-09-28', 5, 15, 5),
('Pas fan de Time, je trouve que le la rejouabilité et le suspense était bâclé.', '2025-01-27', 1, 14, 4),
('Le concept de Pictionary et son le rythme m''ont conquis, je le recommande vivement.', '2024-09-08', 10, 12, 3),
('Une expérience mémorable avec Monopoly, entre la convivialité et la stratégie.', '2024-05-21', 4, 2, 4),
('J''aime bien Qui Est-ce? pour son la stratégie et l''originalité, cependant la rejouabilité est un peu limitée.', '2025-01-21', 2, 19, 2),
('J''ai adoré Trivial Pursuit, surtout pour l''interaction entre joueurs, c''était un vrai plaisir à jouer.', '2025-03-20', 8, 11, 2),
('Uno allie la rejouabilité et le suspense à une prise en main rapide, parfait pour tous les publics.', '2025-03-03', 5, 1, 5),
('Uno est intéressant grâce à son la stratégie, mais certains aspects mériteraient d''être améliorés.', '2024-12-09', 1, 1, 3),
('J''ai adoré Cluedo, surtout pour la durée de partie, c''était un vrai plaisir à jouer.', '2025-01-10', 3, 4, 4),
('Time allie les règles simples et la stratégie à une prise en main rapide, parfait pour tous les publics.', '2025-03-18', 9, 14, 1),
('Une expérience mémorable avec Time, entre la rejouabilité et l''ambiance.', '2024-06-19', 4, 14, 5),
('Pas fan de Les Loups-Garous de Thiercelieux, je trouve que le le suspense et la stratégie était bâclé.', '2025-04-09', 1, 15, 5),
('Déçu par Les Loups-Garous de Thiercelieux, je trouve que l''ambiance n''est pas exploité à son plein potentiel.', '2024-07-25', 3, 15, 5),
('Déçu par Trivial Pursuit, je trouve que les règles simples n''est pas exploité à son plein potentiel.', '2024-10-11', 6, 11, 5),
('Dobble est intéressant grâce à son la rejouabilité, mais certains aspects mériteraient d''être améliorés.', '2025-01-07', 10, 7, 1),
('Déçu par 7 Familles, je trouve que l''interaction entre joueurs n''est pas exploité à son plein potentiel.', '2024-07-27', 1, 18, 5),
('Déçu par Time, je trouve que les règles simples n''est pas exploité à son plein potentiel.', '2024-10-07', 7, 14, 1),
('Le concept de Monopoly et son les graphismes m''ont conquis, je le recommande vivement.', '2024-06-05', 6, 2, 5),
('J''aime bien Les Loups-Garous de Thiercelieux pour son la rejouabilité et la durée de partie, cependant la rejouabilité est un peu limitée.', '2025-02-06', 7, 15, 1),
('Mille Bornes allie le suspense et l''originalité à une prise en main rapide, parfait pour tous les publics.', '2024-08-18', 7, 13, 5),
('Une expérience mémorable avec La Bonne Paye, entre la stratégie et la difficulté.', '2025-03-08', 7, 17, 1),
('Jenga est intéressant grâce à son la durée de partie, mais certains aspects mériteraient d''être améliorés.', '2024-12-30', 9, 8, 1),
('J''ai adoré Time, surtout pour la difficulté, c''était un vrai plaisir à jouer.', '2024-06-02', 2, 14, 2),
('Qui Est-ce? est intéressant grâce à son le rythme, mais certains aspects mériteraient d''être améliorés.', '2024-08-28', 8, 19, 2),
('J''ai adoré Qui Est-ce?, surtout pour la difficulté, c''était un vrai plaisir à jouer.', '2025-01-25', 4, 19, 4),
('Une expérience mémorable avec Qui Est-ce?, entre l''interaction entre joueurs et la difficulté.', '2024-11-26', 1, 19, 1),
('Pas fan de Skyjo, je trouve que le la rejouabilité et la difficulté était bâclé.', '2024-06-02', 3, 3, 4),
('J''aime bien Labyrinthe pour son l''interaction entre joueurs et la convivialité, cependant la rejouabilité est un peu limitée.', '2025-01-03', 4, 16, 5),
('Pas fan de Labyrinthe, je trouve que le l''ambiance et la difficulté était bâclé.', '2024-08-24', 1, 16, 1),
('Dobble allie le suspense et l''originalité à une prise en main rapide, parfait pour tous les publics.', '2025-05-05', 1, 7, 5),
('Le concept de La Bonne Paye et son la convivialité m''ont conquis, je le recommande vivement.', '2024-10-26', 8, 17, 5),
('J''aime bien Twister pour son la rejouabilité et l''ambiance, cependant la rejouabilité est un peu limitée.', '2025-03-17', 9, 9, 3),
('Time est intéressant grâce à son les règles simples, mais certains aspects mériteraient d''être améliorés.', '2024-11-07', 4, 14, 2),
('Trivial Pursuit est intéressant grâce à son la convivialité, mais certains aspects mériteraient d''être améliorés.', '2025-01-12', 5, 11, 2),
('Les Loups-Garous de Thiercelieux est intéressant grâce à son l''interaction entre joueurs, mais certains aspects mériteraient d''être améliorés.', '2024-12-21', 9, 15, 1),
('Risk est intéressant grâce à son les règles simples, mais certains aspects mériteraient d''être améliorés.', '2024-08-27', 7, 5, 4),
('Une expérience mémorable avec Burger Quiz, entre les règles simples et l''ambiance.', '2024-05-26', 10, 20, 3),
('Pas fan de Dobble, je trouve que le le rythme et la difficulté était bâclé.', '2025-05-03', 4, 7, 4),
('Labyrinthe allie la difficulté et la stratégie à une prise en main rapide, parfait pour tous les publics.', '2025-04-04', 2, 16, 3),
('Uno est intéressant grâce à son l''ambiance, mais certains aspects mériteraient d''être améliorés.', '2024-06-02', 2, 1, 1),
('Monopoly allie le rythme et les règles simples à une prise en main rapide, parfait pour tous les publics.', '2024-11-13', 4, 2, 1),
('J''aime bien Cluedo pour son la durée de partie et la stratégie, cependant la rejouabilité est un peu limitée.', '2024-08-26', 9, 4, 4),
('Jenga est intéressant grâce à son la rejouabilité, mais certains aspects mériteraient d''être améliorés.', '2024-10-08', 6, 8, 5),
('7 Familles allie l''ambiance et la rejouabilité à une prise en main rapide, parfait pour tous les publics.', '2024-06-16', 9, 18, 3),
('Déçu par Labyrinthe, je trouve que l''interaction entre joueurs n''est pas exploité à son plein potentiel.', '2025-04-04', 1, 16, 1),
('Pas fan de Uno, je trouve que le la durée de partie et le rythme était bâclé.', '2024-07-23', 1, 1, 4),
('Burger Quiz allie les graphismes et l''ambiance à une prise en main rapide, parfait pour tous les publics.', '2024-06-01', 10, 20, 4),
('J''ai adoré Labyrinthe, surtout pour les règles simples, c''était un vrai plaisir à jouer.', '2024-08-08', 5, 16, 3),
('J''aime bien Labyrinthe pour son l''ambiance et le suspense, cependant la rejouabilité est un peu limitée.', '2025-03-16', 2, 16, 3),
('Déçu par Puissance 4, je trouve que l''ambiance n''est pas exploité à son plein potentiel.', '2025-02-04', 2, 10, 3),
('Labyrinthe est intéressant grâce à son les graphismes, mais certains aspects mériteraient d''être améliorés.', '2025-02-11', 1, 16, 3),
('Le concept de Les Loups-Garous de Thiercelieux et son le rythme m''ont conquis, je le recommande vivement.', '2024-10-11', 1, 15, 4),
('J''ai adoré Jenga, surtout pour l''originalité, c''était un vrai plaisir à jouer.', '2025-03-25', 8, 8, 1),
('Qui Est-ce? allie la rejouabilité et le suspense à une prise en main rapide, parfait pour tous les publics.', '2024-08-05', 3, 19, 3),
('Pas fan de 7 Familles, je trouve que le la difficulté et le suspense était bâclé.', '2024-06-10', 9, 18, 5),
('Une expérience mémorable avec Labyrinthe, entre les règles simples et les graphismes.', '2025-02-09', 5, 16, 3),
('Déçu par Mille Bornes, je trouve que l''originalité n''est pas exploité à son plein potentiel.', '2025-01-19', 4, 13, 1),
('Puissance 4 allie l''ambiance et l''originalité à une prise en main rapide, parfait pour tous les publics.', '2024-07-18', 10, 10, 5),
('Mille Bornes est intéressant grâce à son l''originalité, mais certains aspects mériteraient d''être améliorés.', '2024-10-03', 8, 13, 2),
('J''aime bien Burger Quiz pour son la rejouabilité et la durée de partie, cependant la rejouabilité est un peu limitée.', '2024-05-18', 1, 20, 1),
('Une expérience mémorable avec Qui Est-ce?, entre la convivialité et la difficulté.', '2024-09-30', 1, 19, 4),
('J''aime bien Time pour son l''ambiance et le suspense, cependant la rejouabilité est un peu limitée.', '2024-05-15', 8, 14, 1),
('Déçu par Dobble, je trouve que l''originalité n''est pas exploité à son plein potentiel.', '2025-02-02', 4, 7, 3),
('Twister est intéressant grâce à son l''interaction entre joueurs, mais certains aspects mériteraient d''être améliorés.', '2024-08-08', 10, 9, 4),
('Une expérience mémorable avec Time, entre les graphismes et la stratégie.', '2025-03-15', 7, 14, 2),
('Déçu par Skyjo, je trouve que les règles simples n''est pas exploité à son plein potentiel.', '2024-12-03', 6, 3, 5),
('J''ai adoré Pictionary, surtout pour la difficulté, c''était un vrai plaisir à jouer.', '2024-07-21', 1, 12, 3),
('Une expérience mémorable avec Burger Quiz, entre la stratégie et la convivialité.', '2024-12-08', 5, 20, 1),
('J''aime bien Qui Est-ce? pour son la convivialité et la stratégie, cependant la rejouabilité est un peu limitée.', '2024-05-21', 3, 19, 4),
('J''ai adoré Labyrinthe, surtout pour la rejouabilité, c''était un vrai plaisir à jouer.', '2024-09-24', 5, 16, 2),
('J''aime bien Trivial Pursuit pour son le rythme et l''interaction entre joueurs, cependant la rejouabilité est un peu limitée.', '2025-02-17', 1, 11, 3),
('Pas fan de Time, je trouve que le l''interaction entre joueurs et l''ambiance était bâclé.', '2024-05-29', 9, 14, 5),
('J''aime bien Jenga pour son les graphismes et le suspense, cependant la rejouabilité est un peu limitée.', '2025-04-05', 9, 8, 1),
('Qui Est-ce? est intéressant grâce à son les règles simples, mais certains aspects mériteraient d''être améliorés.', '2025-01-19', 2, 19, 5),
('Déçu par Trivial Pursuit, je trouve que l''interaction entre joueurs n''est pas exploité à son plein potentiel.', '2024-09-12', 9, 11, 4),
('Déçu par Monopoly, je trouve que les règles simples n''est pas exploité à son plein potentiel.', '2024-06-06', 5, 2, 2),
('Pas fan de Les Loups-Garous de Thiercelieux, je trouve que le la stratégie et l''ambiance était bâclé.', '2025-05-06', 3, 15, 5),
('Une expérience mémorable avec La Bonne Paye, entre l''ambiance et les règles simples.', '2024-08-14', 7, 17, 2),
('Le concept de Puissance 4 et son l''ambiance m''ont conquis, je le recommande vivement.', '2024-06-14', 2, 10, 4),
('Le concept de Twister et son le suspense m''ont conquis, je le recommande vivement.', '2024-07-06', 6, 9, 3),
('Déçu par 7 Familles, je trouve que la durée de partie n''est pas exploité à son plein potentiel.', '2025-04-22', 10, 18, 3),
('Pas fan de Trivial Pursuit, je trouve que le la rejouabilité et la durée de partie était bâclé.', '2025-04-23', 3, 11, 1),
('J''ai adoré Scrabble, surtout pour le rythme, c''était un vrai plaisir à jouer.', '2025-05-04', 2, 6, 3),
('J''ai adoré Puissance 4, surtout pour les règles simples, c''était un vrai plaisir à jouer.', '2025-05-04', 2, 10, 5),
('Le concept de 7 Familles et son l''ambiance m''ont conquis, je le recommande vivement.', '2025-04-23', 5, 18, 3),
('Déçu par Puissance 4, je trouve que la difficulté n''est pas exploité à son plein potentiel.', '2025-05-07', 2, 10, 5),
('Burger Quiz est intéressant grâce à son les graphismes, mais certains aspects mériteraient d''être améliorés.', '2025-05-09', 7, 20, 4),
('Jenga est intéressant grâce à son la stratégie, mais certains aspects mériteraient d''être améliorés.', '2025-05-07', 4, 8, 2),
('J''ai adoré Les Loups-Garous de Thiercelieux, surtout pour l''originalité, c''était un vrai plaisir à jouer.', '2025-05-20', 7, 15, 3),
('Time allie la durée de partie et le rythme à une prise en main rapide, parfait pour tous les publics.', '2025-04-28', 7, 14, 1),
('Pas fan de 7 Familles, je trouve que le les graphismes et la durée de partie était bâclé.', '2025-04-29', 3, 18, 3),
('Déçu par Trivial Pursuit, je trouve que les graphismes n''est pas exploité à son plein potentiel.', '2025-04-29', 5, 11, 3),
('Uno est intéressant grâce à son les graphismes, mais certains aspects mériteraient d''être améliorés.', '2025-05-01', 4, 1, 3),
('Une expérience mémorable avec Skyjo, entre les règles simples et la convivialité.', '2025-05-02', 2, 3, 4),
('J''aime bien Cluedo pour son la stratégie et les graphismes, cependant la rejouabilité est un peu limitée.', '2025-05-16', 10, 4, 4),
('J''aime bien Scrabble pour son l''ambiance et la stratégie, cependant la rejouabilité est un peu limitée.', '2025-04-30', 10, 6, 2),
('J''ai adoré Pictionary, surtout pour la rejouabilité, c''était un vrai plaisir à jouer.', '2025-05-19', 8, 12, 1),
('Le concept de Cluedo et son la difficulté m''ont conquis, je le recommande vivement.', '2025-04-24', 4, 4, 2),
('J''ai adoré Twister, surtout pour les règles simples, c''était un vrai plaisir à jouer.', '2025-05-16', 7, 9, 5),
('Une expérience mémorable avec La Bonne Paye, entre la rejouabilité et la difficulté.', '2025-04-24', 4, 17, 4),
('Une expérience mémorable avec Les Loups-Garous de Thiercelieux, entre les graphismes et la durée de partie.', '2025-04-25', 2, 15, 2),
('Pas fan de Skyjo, je trouve que le la difficulté et les graphismes était bâclé.', '2025-04-24', 6, 3, 2),
('Déçu par Cluedo, je trouve que les graphismes n''est pas exploité à son plein potentiel.', '2025-04-28', 7, 4, 5),
('Pas fan de Monopoly, je trouve que le les graphismes et l''interaction entre joueurs était bâclé.', '2025-05-10', 2, 2, 1),
('Time est intéressant grâce à son la convivialité, mais certains aspects mériteraient d''être améliorés.', '2025-05-04', 2, 14, 4),
('J''aime bien Scrabble pour son la durée de partie et la rejouabilité, cependant la rejouabilité est un peu limitée.', '2025-05-03', 5, 6, 1),
('J''ai adoré Mille Bornes, surtout pour les graphismes, c''était un vrai plaisir à jouer.', '2025-05-07', 5, 13, 2),
('Les Loups-Garous de Thiercelieux est intéressant grâce à son le rythme, mais certains aspects mériteraient d''être améliorés.', '2025-04-22', 5, 15, 4),
('Qui Est-ce? est intéressant grâce à son l''originalité, mais certains aspects mériteraient d''être améliorés.', '2025-05-12', 3, 19, 5),
('J''ai adoré Scrabble, surtout pour l''interaction entre joueurs, c''était un vrai plaisir à jouer.', '2025-05-08', 4, 6, 4),
('Une expérience mémorable avec Pictionary, entre les graphismes et la rejouabilité.', '2025-05-16', 8, 12, 1),
('J''ai adoré Time, surtout pour la convivialité, c''était un vrai plaisir à jouer.', '2025-05-01', 7, 14, 2),
('Skyjo allie le rythme et l''interaction entre joueurs à une prise en main rapide, parfait pour tous les publics.', '2025-04-27', 9, 3, 1),
('J''aime bien La Bonne Paye pour son l''ambiance et le rythme, cependant la rejouabilité est un peu limitée.', '2025-05-02', 1, 17, 5),
('Dobble est intéressant grâce à son le suspense, mais certains aspects mériteraient d''être améliorés.', '2025-05-11', 7, 7, 4),
('Uno est intéressant grâce à son le rythme, mais certains aspects mériteraient d''être améliorés.', '2025-05-18', 5, 1, 3),
('Le concept de Scrabble et son les règles simples m''ont conquis, je le recommande vivement.', '2025-05-17', 8, 6, 5),
('Le concept de Puissance 4 et son la convivialité m''ont conquis, je le recommande vivement.', '2025-04-29', 7, 10, 5),
('Une expérience mémorable avec Scrabble, entre les graphismes et la rejouabilité.', '2025-05-06', 2, 6, 1),
('Une expérience mémorable avec La Bonne Paye, entre la difficulté et l''originalité.', '2025-05-01', 7, 17, 3),
('Risk est intéressant grâce à son la difficulté, mais certains aspects mériteraient d''être améliorés.', '2025-05-11', 7, 5, 4),
('J''aime bien Skyjo pour son les règles simples et la durée de partie, cependant la rejouabilité est un peu limitée.', '2025-04-29', 2, 3, 2),
('Déçu par Time, je trouve que le suspense n''est pas exploité à son plein potentiel.', '2025-04-25', 4, 14, 2),
('Une expérience mémorable avec Monopoly, entre les graphismes et le suspense.', '2025-04-28', 6, 2, 3),
('Pas fan de Cluedo, je trouve que le l''interaction entre joueurs et la difficulté était bâclé.', '2025-04-30', 8, 4, 1),
('Une expérience mémorable avec Skyjo, entre le rythme et la rejouabilité.', '2025-05-06', 1, 3, 3),
('Pas fan de Labyrinthe, je trouve que le la difficulté et l''interaction entre joueurs était bâclé.', '2025-05-01', 7, 16, 4),
('J''ai adoré Les Loups-Garous de Thiercelieux, surtout pour le suspense, c''était un vrai plaisir à jouer.', '2025-04-30', 6, 15, 1),
('Le concept de Qui Est-ce? et son le rythme m''ont conquis, je le recommande vivement.', '2025-05-08', 3, 19, 5),
('Une expérience mémorable avec Qui Est-ce?, entre les graphismes et la rejouabilité.', '2025-05-14', 1, 19, 5),
('Qui Est-ce? allie l''originalité et le rythme à une prise en main rapide, parfait pour tous les publics.', '2025-04-25', 4, 19, 5),
('Risk allie la durée de partie et la difficulté à une prise en main rapide, parfait pour tous les publics.', '2025-05-13', 5, 5, 5),
('Pas fan de Cluedo, je trouve que le les graphismes et la stratégie était bâclé.', '2025-05-10', 2, 4, 1),
('Déçu par Skyjo, je trouve que la difficulté n''est pas exploité à son plein potentiel.', '2025-05-17', 4, 3, 3),
('J''aime bien 7 Familles pour son les graphismes et la difficulté, cependant la rejouabilité est un peu limitée.', '2025-04-30', 6, 18, 1),
('Pas fan de Les Loups-Garous de Thiercelieux, je trouve que le la convivialité et la durée de partie était bâclé.', '2025-05-12', 2, 15, 5),
('Déçu par Dobble, je trouve que la rejouabilité n''est pas exploité à son plein potentiel.', '2025-05-09', 1, 7, 4),
('Pictionary est intéressant grâce à son la durée de partie, mais certains aspects mériteraient d''être améliorés.', '2025-04-22', 9, 12, 3),
('J''ai adoré Cluedo, surtout pour les graphismes, c''était un vrai plaisir à jouer.', '2025-05-07', 3, 4, 4),
('J''ai adoré Mille Bornes, surtout pour le rythme, c''était un vrai plaisir à jouer.', '2025-04-28', 9, 13, 1),
('J''ai adoré Skyjo, surtout pour le suspense, c''était un vrai plaisir à jouer.', '2025-05-01', 9, 3, 3),
('Déçu par Risk, je trouve que les graphismes n''est pas exploité à son plein potentiel.', '2025-04-24', 6, 5, 2),
('J''aime bien 7 Familles pour son les graphismes et l''ambiance, cependant la rejouabilité est un peu limitée.', '2025-04-28', 10, 18, 1),
('Pas fan de Twister, je trouve que le les règles simples et la convivialité était bâclé.', '2025-05-13', 3, 9, 2),
('La Bonne Paye est intéressant grâce à son l''originalité, mais certains aspects mériteraient d''être améliorés.', '2025-05-11', 6, 17, 2),
('Skyjo est intéressant grâce à son la stratégie, mais certains aspects mériteraient d''être améliorés.', '2025-04-30', 8, 3, 5),
('J''aime bien Trivial Pursuit pour son l''ambiance et les règles simples, cependant la rejouabilité est un peu limitée.', '2025-05-10', 1, 11, 4),
('J''aime bien Scrabble pour son les règles simples et l''ambiance, cependant la rejouabilité est un peu limitée.', '2025-04-27', 10, 6, 2),
('Pictionary est intéressant grâce à son le rythme, mais certains aspects mériteraient d''être améliorés.', '2025-04-21', 1, 12, 4),
('Pas fan de Les Loups-Garous de Thiercelieux, je trouve que le la durée de partie et les graphismes était bâclé.', '2025-05-09', 7, 15, 4),
('Une expérience mémorable avec Labyrinthe, entre les règles simples et le suspense.', '2025-05-01', 9, 16, 4),
('Une expérience mémorable avec Risk, entre l''originalité et l''interaction entre joueurs.', '2025-05-11', 2, 5, 1),
('Déçu par Scrabble, je trouve que la durée de partie n''est pas exploité à son plein potentiel.', '2025-05-06', 3, 6, 1),
('Pas fan de Labyrinthe, je trouve que le les graphismes et l''ambiance était bâclé.', '2025-05-21', 4, 16, 3),
('J''aime bien Monopoly pour son la convivialité et l''originalité, cependant la rejouabilité est un peu limitée.', '2025-05-13', 8, 2, 4),
('Déçu par Scrabble, je trouve que l''originalité n''est pas exploité à son plein potentiel.', '2025-05-21', 10, 6, 5),
('Pas fan de Monopoly, je trouve que le les graphismes et la convivialité était bâclé.', '2025-05-16', 9, 2, 5),
('J''aime bien 7 Familles pour son l''ambiance et l''interaction entre joueurs, cependant la rejouabilité est un peu limitée.', '2025-05-07', 5, 18, 5),
('J''ai adoré Skyjo, surtout pour la convivialité, c''était un vrai plaisir à jouer.', '2025-05-11', 10, 3, 1),
('Qui Est-ce? allie le suspense et l''ambiance à une prise en main rapide, parfait pour tous les publics.', '2025-05-16', 5, 19, 3),
('J''aime bien Trivial Pursuit pour son la difficulté et les règles simples, cependant la rejouabilité est un peu limitée.', '2025-04-25', 1, 11, 3),
('J''ai adoré Scrabble, surtout pour la durée de partie, c''était un vrai plaisir à jouer.', '2025-05-21', 10, 6, 2),
('J''aime bien La Bonne Paye pour son la difficulté et l''originalité, cependant la rejouabilité est un peu limitée.', '2025-05-12', 5, 17, 5),
('Pas fan de Labyrinthe, je trouve que le les règles simples et la stratégie était bâclé.', '2025-05-10', 6, 16, 1),
('Twister allie le rythme et la difficulté à une prise en main rapide, parfait pour tous les publics.', '2025-04-23', 6, 9, 4),
('Le concept de Qui Est-ce? et son la durée de partie m''ont conquis, je le recommande vivement.', '2025-05-19', 3, 19, 5),
('Cluedo allie l''interaction entre joueurs et l''originalité à une prise en main rapide, parfait pour tous les publics.', '2025-04-30', 4, 4, 3),
('Le concept de Uno et son l''interaction entre joueurs m''ont conquis, je le recommande vivement.', '2025-05-10', 7, 1, 5),
('Une expérience mémorable avec La Bonne Paye, entre le rythme et l''originalité.', '2025-05-17', 3, 17, 5),
('Une expérience mémorable avec Cluedo, entre la stratégie et la convivialité.', '2025-04-28', 7, 4, 1),
('Une expérience mémorable avec Skyjo, entre la convivialité et les graphismes.', '2025-05-04', 6, 3, 2),
('J''aime bien Time pour son la stratégie et la convivialité, cependant la rejouabilité est un peu limitée.', '2025-04-26', 10, 14, 4),
('Une expérience mémorable avec Jenga, entre la durée de partie et la convivialité.', '2025-05-06', 4, 8, 1),
('Trivial Pursuit est intéressant grâce à son l''originalité, mais certains aspects mériteraient d''être améliorés.', '2025-04-27', 1, 11, 1),
('Pas fan de Burger Quiz, je trouve que le la difficulté et l''interaction entre joueurs était bâclé.', '2025-05-15', 8, 20, 5),
('Time est intéressant grâce à son l''originalité, mais certains aspects mériteraient d''être améliorés.', '2025-05-15', 1, 14, 5),
('Une expérience mémorable avec Risk, entre l''originalité et la convivialité.', '2025-04-24', 9, 5, 2),
('Pas fan de Twister, je trouve que le les règles simples et les graphismes était bâclé.', '2025-05-05', 6, 9, 5),
('Une expérience mémorable avec Burger Quiz, entre les règles simples et la rejouabilité.', '2025-05-12', 9, 20, 1),
('Pas fan de Time, je trouve que le la convivialité et la stratégie était bâclé.', '2025-05-21', 4, 14, 4);

